name: repo_viewer
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^4.0.6
  flash: ^2.0.3+2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^1.1.0
  hooks_riverpod: ^1.0.3
  intl: ^0.17.0
  json_annotation: ^4.4.0
  material_design_icons_flutter: ^5.0.6595
  oauth2: ^2.0.0
  sembast: ^3.2.0

dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
